# Generated by Django 4.2.4 on 2023-10-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apistatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apistatistics',
            options={'verbose_name': '访问记录表', 'verbose_name_plural': '访问记录表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '访问记录表', 'verbose_name_plural': '访问记录表'},
        ),
        migrations.AlterModelTable(
            name='apistatistics',
            table='sys_visit',
        ),
        migrations.AlterModelTable(
            name='book',
            table='tb_book',
        ),
    ]
