# Generated by Django 4.2.4 on 2023-10-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_alter_accesstimeoutlogs_table_alter_oplogs_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessTimeOutLogs',
        ),
        migrations.DeleteModel(
            name='OpLogs',
        ),
    ]
